# Generated by Django 4.2.9 on 2024-02-28 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0003_project_status_alter_project_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="date_created",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 28, 3, 49, 37, 253834, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
