# Generated by Django 4.2.9 on 2024-02-28 03:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0004_alter_project_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.FileField(blank=True, upload_to="project_images/"),
        ),
        migrations.AlterField(
            model_name="project",
            name="date_created",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 2, 28, 3, 50, 59, 263066, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
